### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Condutiarii** [LeonPupier/Mensible#13]
Hi,

Not a bug but a clarification for using this new version with Python on Windows, the Python commands in your guide are not the same on this operating system. The following commands work:

`py -m pip install -r requirements.txt`

and

`py main.py`

**Comment by LeonPupier** [comment]
Thanks for the help, I added an info in the install section in the [Readme](https://github.com/LeonPupier/Mensible/blob/master/README.md) :)
*Leon*
