### ISSUE TITLE
 I cant open the file

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [LeonPupier/Mensible#4]
my friend I cant open the file...appear this Failed to obtain/convert traceback!

**Comment by LeonPupier** [comment]
Hello, I just uploaded version 1.4.4, please download "Mensible_Setup.exe", it will download the latest version and it should fix all your problems :)
Keep me informed I will be responsive

**Comment by KENPOKASMMA1982** [comment]
my friend thanks so much where not ignore my message!but still I have problem dude    Traceback (most recent call last):
  File "Downloader.pyw", line 64, in <module>
  File "configparser.py", line 959, in __getitem__
KeyError: 'CONFIG'

**Comment by LeonPupier** [comment]
No problem I'm here to help!
Can you tell me if the application installation folder looks like this:
![folder](https://user-images.githubusercontent.com/100092382/164459581-238e04a4-3ed1-4b8b-b70c-0c25c2d253bf.png)

**Comment by LeonPupier** [comment]
After having tried it on many computers running Windows 10, if you download and run the following file and let yourself be guided by the installer you should have no problem:
[Mensible_Setup.exe](https://github.com/LeonPupier/Mensible/releases/download/v1.4.4/Mensible_Setup.exe)

**Comment by KENPOKASMMA1982** [comment]
mmm my friend appear content,description,mensible exe and readme!nothing else

**Comment by LeonPupier** [comment]
It is necessary to launch the application with the executable "Mensible Launcher.exe" to solve your problem, you must surely launch the application directly with "Mensible.exe" which causes your problem.

**Comment by LeonPupier** [comment]
Did you try with the file I put in the discussion?

**Comment by KENPOKASMMA1982** [comment]
MY FRIEND CAN YOY ENTER ON MY PC WITH TEAM VIEWER PLEASE?I WILL PRECIATE IT SO MUCH!

**Comment by LeonPupier** [comment]
I can not currently, please excuse me, the solution I provided is really the right one... I do not understand why it does not work with you :(

**Comment by KENPOKASMMA1982** [comment]
I understand man!dont worry!hey it works!I can open the file now...but are you sure download from spotify?

**Comment by LeonPupier** [comment]
It's great if the problem is solved then! Spotify support is currently in Beta as it was recently implemented and needs to be refined, this will happen over time I don't have a date yet. I'll mark the issue as solved then, I'll be in touch if needed, have a great day!
